version: "3.8"

networks:
  khem:
    driver: bridge

services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'khem'
      MYSQL_USER: 'khem'
      MYSQL_PASSWORD: 'khem'
      MYSQL_ROOT_PASSWORD: 'khem'
    ports:
      - 1022:3306
    expose:
      - 3306
    healthcheck:
      test: "/usr/bin/mysql --user=khem --password=khem --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 20


  node-service:
    build:
      context: ./back_end
    networks:
      - khem
    ports:
      - 1023:5000
    restart: unless-stopped
    environment:
      WAIT_HOSTS: 193.137.5.79:3306
      WAIT_BEFORE_HOSTS: 10
    depends_on:
      - db
    

  react-service:
    build:
      context: ./front_end/trabalho_final
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - db


